#include<SFML\Graphics.hpp>

namespace
{
	const int widhtMap = 275;
	const int heightMap = 43;
	sf::String lvl_One[heightMap] =
	{
	"gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg",
	"gg                                                                                                                                                                                                                                              gggggggggggggggggggggggggggggggggg",
	"gg                                                                                                                                                                                                                                                                              gg",
	"gg                                                                                         V                                                                                                                                                                                    gg",
	"gg                                                                                                                                                                                                  gggggggggggggggggggggg                                                      gg",
	"gg                                                                                                                                                                           gg          C      TTgg       H            gg             gggggggg                                 gg",
	"gg                                                                                                                                                          ggggg       ggggggg  ggTTT  ggTTTT                          gg          gggg                                        gg",
	"gg                            E             C              C      C           C     E                           C                                C                           gg                                         gg        ggg                                           gg",
	"gg  C             C ggggggggggggggTTTTggggggggggggggTTTTTggggggTTgggTTggTTggggggggggggggg         C       ggggggggggg          C             gggggggg                        gg                                       ggggg                                                     gg",
	"gggggg           gggg      ggLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLgg                   gg                          gggggggg                                        gg                                         gggggg                                         B        gg",
	"gg        C                ggLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLgg                                                                                               gg                                                                                                 gg",
	"gg       ggg               ggggggggggggggggggggggggggggggggggggggggggggggggggg                                                                                               gg          E   E   E     C C C                    gggg                                            gg",
	"gg                  C                                                                                                                                                        gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggTTTTgggggggggggTTTTTgggg",
	"gg                gggg                                                                                                                                                       ggLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLgg",
	"gg  CC                       gg                                                g                                                                                             ggLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLgg",
	"ggTTTT                       gg E                     C                                 C                                           gg                                       ggggggggggggggggggggggggggLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLgg",
	"gg                           ggggggTTTgggTTTgggTTTgggggggg                            ggggg                                                                                                           gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg",
	"gg                                                       ggg        gggggg       g                 gggg       gggg         gg               gggg      E                             V                                                                                           gg",
	"gg                                                                                                                                                   gg                                                                                                                         gg",
	"ggLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLgg                                                                                                                         gg",
	"ggLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLgggg     C         C               C               E       C                     E           C                  C          gg",
	"gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg        SSSSSSSSSSSSSSSSS          SSSSSSSSSSSSSSSSSSSSSSSSSS         SS          SS",
	"gg                                                                                                                                                                                                                                                                           SSSSS",
	"gg                                                                                                                                                                                                                                                                         SSSSSSS",
	"gg                                                                                                                                                                                                                                                                              SS",
	"gg                                                                                                                                                                                                   E      C       C              C        C     C                C   C        SS",
	"gg                                                                                                                                                                                                SSSSSSSSSSSSSSSSSSSSS          SSSSSSSSSSSSSSSSSSSSSS        SSSSSSSSSS       SS",
	"gg           C                                                                                                                                                                                  SSS                                                                             SS",
	"gg           GG                                                                                                        C                                                                      SSS                                                                             SSSS",
	"gg    C                                                                                               C                tt                                                                   SSS             C                                                          C        SS",
	"ggGGGGGGG                                                                               C          GGGtttGG                                   E    C C C C    E                           SSS             SSSSS       SS                                              SS        SS",
	"gg                                                        tt       C   C     C E        ttGG                       GG          C       GGGGGGGSSSSSSSSSSSSSSSSSSSSSS                   SSS             S              SS                                                        SS",
	"gg                     C C                C                       GGGGtttttGGGGGGG                                            GG                                   S         C       SSS    S                         SS                                                       SSS",
	"gg                    GGGGG       C     GGGGtt      GG        GG                                                                                                   SSSSSSSSSSSSSSSSSSS      S E                       SS                                               C        SS",
	"gg                                GG                                                                                                                                                        SSSSSSSS     C            SS                                              SS        SS",
	"gg         C C C C E                                                                                                                                                                                   SSSSS          SS                                                      C SS",
	"gg       GGGGGGGGGGGGG                                                                                                                                                                                                SS                                                      SSSS",
	"gg  C                         GG                  C                                                         C                                                                                                     C SSSS                                                        SS",
	"ggGGGG                                 GG         GG       GG       C    tt                        C       GG                          C          C             C                                                SSSS                                   E              C  C  C  SS",
	"gg                                                                 GG                             GG                C         C       GG         SSSS         SSSSSSS                              C          C                    SS        SSSSSSSSSSSSSSSSS         SSSSSSSSSSS",
	"gg   P         C     g      C                                             g C C C C E C   Eg                        GG        GG                                              S C C C E  SS        SSS       SSS                                                                SS",
	"ggGGGGGGGGGGGGGGGGGGGgWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWgGGGGGGGGGGGGGGGGgWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWSSSSSSSSSSSSSWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWSSSS",
	"gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg"
	};

}